# Tcl package index file, Chariot version 6.25
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

if [package vsatisfies [package provide Tcl] 8.1] {
package ifneeded ChariotExt 6.70 [list tclPkgSetup $dir ChariotExt 6.70 {{ChariotExt.dll load ChariotExt}}]
} else {
package ifneeded Chariot 6.70 [list tclPkgSetup $dir Chariot 6.70 {{Chariot.dll load Chariot}}]
}
